import type { AnalyticsRow, ProfitabilityCell, StabilitySegment } from './types';

export const profitabilityMatrix: ProfitabilityCell[] = [
  { profit: 'PPP', sales: 'A', count: 16 },
  { profit: 'PPP', sales: 'B', count: 1 },
  { profit: 'PPP', sales: 'C', count: 0 },
  { profit: 'PP', sales: 'A', count: 2 },
  { profit: 'PP', sales: 'B', count: 10 },
  { profit: 'PP', sales: 'C', count: 1 },
  { profit: 'P', sales: 'A', count: 0 },
  { profit: 'P', sales: 'B', count: 3 },
  { profit: 'P', sales: 'C', count: 25 },
  { profit: '-P', sales: 'A', count: 0 },
  { profit: '-P', sales: 'B', count: 0 },
  { profit: '-P', sales: 'C', count: 1 },
];

export const stabilitySegments: StabilitySegment[] = [
  {
    tier: 'X',
    label: 'Стабильная',
    count: 1,
    share: 1.7,
    description: 'Коэф. вариации продаж < 10%',
  },
  {
    tier: 'Y',
    label: 'Средняя',
    count: 14,
    share: 23.7,
    description: 'Коэф. вариации 10–25%',
  },
  {
    tier: 'Z',
    label: 'Нестабильная',
    count: 44,
    share: 74.6,
    description: 'Коэф. вариации > 25%',
  },
];

export const mockAnalyticsRows: AnalyticsRow[] = [
  {
    id: '1',
    name: 'Мяч массажный для стоп — шар мфр для пилатеса',
    barcode: 'ACRB1MS106WH',
    channel: 'WB',
    tags: ['PPP', 'A', 'Y'],
    profit: 'PPP',
    sales: 'A',
    stability: 'Y',
    revenue: 17725,
    margin: 38.2,
    cost: 380,
    stock: 12,
    unitsSold: 30,
  },
  {
    id: '2',
    name: 'Бандаж для лица подбородка многоразовый силиконовый',
    barcode: 'ACRF1BN201GR',
    channel: 'WB',
    tags: ['PPP', 'A', 'Z'],
    profit: 'PPP',
    sales: 'A',
    stability: 'Z',
    revenue: 17431,
    margin: 41.5,
    cost: 420,
    stock: 8,
    unitsSold: 16,
  },
  {
    id: '3',
    name: 'Мешок для стирки белья — сетка крупная — 3 штуки',
    barcode: 'AHMA3BW202WH',
    channel: 'WB',
    tags: ['PPP', 'A', 'Y'],
    profit: 'PPP',
    sales: 'A',
    stability: 'Y',
    revenue: 17390,
    margin: 35.8,
    cost: 290,
    stock: 0,
    unitsSold: 22,
  },
  {
    id: '4',
    name: 'Таблетница на неделю — 2 приема круглая серая',
    barcode: 'ACRA7TB301GR',
    channel: 'WB',
    tags: ['PPP', 'A', 'Z'],
    profit: 'PPP',
    sales: 'A',
    stability: 'Z',
    revenue: 14478,
    margin: 33.0,
    cost: 240,
    stock: 0,
    unitsSold: 21,
  },
  {
    id: '5',
    name: 'Большой мешок для стирки 60×80',
    barcode: 'AHMA1BW101WH',
    channel: 'WB',
    tags: ['PPP', 'A', 'Y'],
    profit: 'PPP',
    sales: 'A',
    stability: 'Y',
    revenue: 12380,
    margin: 37.2,
    cost: 310,
    stock: 24,
    unitsSold: 19,
  },
  {
    id: '6',
    name: 'Шар мфр для пилатеса фитнес',
    barcode: 'ACRM2MS302BL',
    channel: 'OZON',
    tags: ['PP', 'B', 'Y'],
    profit: 'PP',
    sales: 'B',
    stability: 'Y',
    revenue: 8120,
    margin: 28.4,
    cost: 410,
    stock: 3,
    unitsSold: 11,
  },
  {
    id: '7',
    name: 'Бандаж для лица прозрачный',
    barcode: 'ACRF1BN202CL',
    channel: 'OZON',
    tags: ['PP', 'B', 'Y'],
    profit: 'PP',
    sales: 'B',
    stability: 'Y',
    revenue: 7430,
    margin: 31.2,
    cost: 440,
    stock: 2,
    unitsSold: 9,
  },
  {
    id: '8',
    name: 'Набор органайзеров прозрачных',
    barcode: 'AHMA1OR501TR',
    channel: 'WB',
    tags: ['PP', 'B', 'X'],
    profit: 'PP',
    sales: 'B',
    stability: 'X',
    revenue: 6210,
    margin: 26.8,
    cost: 260,
    stock: 4,
    unitsSold: 8,
  },
  {
    id: '9',
    name: 'Подставка для планшета',
    barcode: 'ACRA1ST201BL',
    channel: 'OZON',
    tags: ['P', 'C', 'X'],
    profit: 'P',
    sales: 'C',
    stability: 'X',
    revenue: 2890,
    margin: 15.2,
    cost: 320,
    stock: 2,
    unitsSold: 3,
  },
  {
    id: '10',
    name: 'Кольцо для пилатеса мягкое',
    barcode: 'ACRP1RG301GR',
    channel: 'WB',
    tags: ['P', 'C', 'X'],
    profit: 'P',
    sales: 'C',
    stability: 'X',
    revenue: 2410,
    margin: 18.0,
    cost: 280,
    stock: 5,
    unitsSold: 4,
  },
  {
    id: '11',
    name: 'Карандаш с ластиком',
    barcode: 'ACPN1RC101BL',
    channel: 'WB',
    tags: ['P', 'C', 'Z'],
    profit: 'P',
    sales: 'C',
    stability: 'Z',
    revenue: 980,
    margin: 12.4,
    cost: 95,
    stock: 15,
    unitsSold: 2,
  },
  {
    id: '12',
    name: 'Резиновый массажер для стоп',
    barcode: 'ACRM3RB201BL',
    channel: 'OZON',
    tags: ['-P', 'C', 'Z'],
    profit: '-P',
    sales: 'C',
    stability: 'Z',
    revenue: 420,
    margin: -8.5,
    cost: 380,
    stock: 18,
    unitsSold: 1,
  },
];

export const mockAnalyticsSummary = {
  totalProducts: 59,
  withCost: 59,
  withoutCost: 0,
  withSales: 59,
  stable: 1,
  unstable: 44,
};
