import type { Review, ReviewsSummary, ReviewRating } from './types';

export const mockReviews: Review[] = [
  {
    id: 'r1',
    productName: 'Мяч массажный для стоп с шипами',
    productBarcode: 'ACRM1MS501WH',
    channel: 'WB',
    rating: 5,
    text: 'Отличный мяч, жёсткость как раз для проработки стоп. Заказывала повторно для мамы — она в восторге, теперь делает массаж каждый вечер.',
    author: 'Анна К.',
    date: '2026-05-28T09:14:00Z',
    sentiment: 'positive',
    responseStatus: 'answered',
    responseText: 'Спасибо за отзыв! Рады, что мяч подошёл.',
    responseDate: '2026-05-28T14:02:00Z',
  },
  {
    id: 'r2',
    productName: 'Бандаж для лица подбородка многоразовый силиконовый',
    productBarcode: 'ACRF1BN201GR',
    channel: 'WB',
    rating: 4,
    text: 'В целом нормально, но размер немного маловат — давит за ушами. Эффект есть после недели использования.',
    author: 'Марина С.',
    date: '2026-05-27T18:32:00Z',
    sentiment: 'positive',
    responseStatus: 'answered',
    responseText: 'Спасибо за обратную связь, учтём при следующей партии.',
    responseDate: '2026-05-28T08:11:00Z',
  },
  {
    id: 'r3',
    productName: 'Таблетница на неделю — 2 приема круглая серая',
    productBarcode: 'ACRA7TB301GR',
    channel: 'WB',
    rating: 1,
    text: 'Крышки открываются сами в сумке, все таблетки перемешались. Очень неудобно, не рекомендую.',
    author: 'Игорь П.',
    date: '2026-05-27T11:08:00Z',
    sentiment: 'negative',
    responseStatus: 'pending',
  },
  {
    id: 'r4',
    productName: 'Мешок для стирки белья — сетка крупная — 3 штуки',
    productBarcode: 'ACRF1MS301WH',
    channel: 'OZON',
    rating: 5,
    text: 'Три мешка разного размера, всё на молниях, ткань плотная. Стираю бельё уже месяц — никаких претензий.',
    author: 'Ольга В.',
    date: '2026-05-26T15:44:00Z',
    sentiment: 'positive',
    responseStatus: 'answered',
    responseText: 'Благодарим за отзыв!',
    responseDate: '2026-05-26T19:20:00Z',
  },
  {
    id: 'r5',
    productName: 'Шар мфр для пилатеса фитнес мяч',
    productBarcode: 'ACRM2MS302BL',
    channel: 'OZON',
    rating: 2,
    text: 'Шар пришёл с заломом, после накачки не круглый. Поддержка молчит уже три дня.',
    author: 'Денис Р.',
    date: '2026-05-26T10:02:00Z',
    sentiment: 'negative',
    responseStatus: 'ignored',
  },
  {
    id: 'r6',
    productName: 'Кольцо для пилатеса мягкое',
    productBarcode: 'ACRP1RG301GR',
    channel: 'WB',
    rating: 5,
    text: 'Кольцо мягкое, ручки удобные, не скользят. За свои деньги — отличное.',
    author: 'Светлана А.',
    date: '2026-05-25T20:11:00Z',
    sentiment: 'positive',
    responseStatus: 'answered',
    responseText: 'Спасибо! Рады, что понравилось.',
    responseDate: '2026-05-26T09:00:00Z',
  },
  {
    id: 'r7',
    productName: 'Большой мешок для стирки — 60×80 сетка крупная',
    productBarcode: 'AHMA3BW202WH',
    channel: 'WB',
    rating: 3,
    text: 'Размер большой, как и заявлено. Но молния туговата, надеюсь не порвётся.',
    author: 'Татьяна Л.',
    date: '2026-05-25T13:25:00Z',
    sentiment: 'neutral',
    responseStatus: 'pending',
  },
  {
    id: 'r8',
    productName: 'Таблетница на неделю 2 приема',
    productBarcode: 'ACRB1MS106WH',
    channel: 'WB',
    rating: 5,
    text: 'Удобная, разделение по дням и приёмам. Беру с собой в командировки.',
    author: 'Алексей М.',
    date: '2026-05-24T08:50:00Z',
    sentiment: 'positive',
    responseStatus: 'answered',
    responseText: 'Спасибо за отзыв!',
    responseDate: '2026-05-24T11:30:00Z',
  },
  {
    id: 'r9',
    productName: 'Бандаж для лица прозрачный',
    productBarcode: 'ACRF1BN202CL',
    channel: 'OZON',
    rating: 1,
    text: 'Прозрачный материал быстро мутнеет, через две стирки стал жёлтым. Деньги на ветер.',
    author: 'Виктория Н.',
    date: '2026-05-23T17:18:00Z',
    sentiment: 'negative',
    responseStatus: 'pending',
  },
  {
    id: 'r10',
    productName: 'Мяч массажный для стоп с шипами',
    productBarcode: 'ACRM1MS501WH',
    channel: 'OZON',
    rating: 4,
    text: 'Хорошее качество, шипы не царапают. Минус — запах резины первые дни.',
    author: 'Павел Д.',
    date: '2026-05-22T12:40:00Z',
    sentiment: 'positive',
    responseStatus: 'answered',
    responseText: 'Запах уходит через 2-3 дня проветривания, спасибо за отзыв.',
    responseDate: '2026-05-22T18:00:00Z',
  },
  {
    id: 'r11',
    productName: 'Набор органайзеров прозрачных',
    productBarcode: 'AHMA1OR501TR',
    channel: 'WB',
    rating: 5,
    text: 'Всё подошло идеально под мои шкафы. Прозрачные — видно что внутри, очень удобно.',
    author: 'Наталья О.',
    date: '2026-05-22T09:15:00Z',
    sentiment: 'positive',
    responseStatus: 'answered',
    responseText: 'Спасибо!',
    responseDate: '2026-05-22T10:00:00Z',
  },
  {
    id: 'r12',
    productName: 'Таблетница на неделю 2 приема чёрная',
    productBarcode: 'ACRA7TB301BL',
    channel: 'WB',
    rating: 2,
    text: 'Пластик тонкий, одна крышечка отломилась через неделю. Ожидала большего.',
    author: 'Елена З.',
    date: '2026-05-21T19:33:00Z',
    sentiment: 'negative',
    responseStatus: 'pending',
  },
  {
    id: 'r13',
    productName: 'Подставка для планшета',
    productBarcode: 'ACRA1ST201BL',
    channel: 'OZON',
    rating: 4,
    text: 'Устойчивая, регулируется углами. Для планшета 11 дюймов — самое то.',
    author: 'Сергей Б.',
    date: '2026-05-20T14:22:00Z',
    sentiment: 'positive',
    responseStatus: 'answered',
    responseText: 'Спасибо за обратную связь!',
    responseDate: '2026-05-20T16:00:00Z',
  },
  {
    id: 'r14',
    productName: 'Шар мфр для пилатеса фитнес мяч',
    productBarcode: 'ACRM2MS302BL',
    channel: 'WB',
    rating: 5,
    text: 'Использую для МФР после тренировок — отлично разминает мышцы, плотный.',
    author: 'Ирина Г.',
    date: '2026-05-19T11:05:00Z',
    sentiment: 'positive',
    responseStatus: 'answered',
    responseText: 'Спасибо!',
    responseDate: '2026-05-19T13:00:00Z',
  },
  {
    id: 'r15',
    productName: 'Бандаж для лица подбородка многоразовый силиконовый',
    productBarcode: 'ACRF1BN201GR',
    channel: 'OZON',
    rating: 3,
    text: 'Эффект слабый, нужно носить долго. Материал нормальный, но результата быстрого нет.',
    author: 'Юлия Х.',
    date: '2026-05-18T16:48:00Z',
    sentiment: 'neutral',
    responseStatus: 'pending',
  },
  {
    id: 'r16',
    productName: 'Кольцо для пилатеса мягкое',
    productBarcode: 'ACRP1RG301GR',
    channel: 'OZON',
    rating: 5,
    text: 'Прекрасное кольцо для домашних тренировок. Не жёсткое, не мягкое — идеальный баланс.',
    author: 'Мария Ф.',
    date: '2026-05-17T20:00:00Z',
    sentiment: 'positive',
    responseStatus: 'answered',
    responseText: 'Благодарим за отзыв!',
    responseDate: '2026-05-18T09:00:00Z',
  },
  {
    id: 'r17',
    productName: 'Мешок для стирки белья — сетка крупная — 3 штуки',
    productBarcode: 'ACRF1MS301WH',
    channel: 'WB',
    rating: 4,
    text: 'Хорошие мешки, но молния у самого большого подкачала — заела с первого раза.',
    author: 'Андрей К.',
    date: '2026-05-16T10:30:00Z',
    sentiment: 'positive',
    responseStatus: 'answered',
    responseText: 'Спасибо, передадим производству.',
    responseDate: '2026-05-16T15:00:00Z',
  },
  {
    id: 'r18',
    productName: 'Таблетница на неделю — 2 приема круглая серая',
    productBarcode: 'ACRA7TB301GR',
    channel: 'OZON',
    rating: 1,
    text: 'Пришла сломанной, упаковка была целой. Возврат оформить сложно.',
    author: 'Олег Т.',
    date: '2026-05-15T13:12:00Z',
    sentiment: 'negative',
    responseStatus: 'ignored',
  },
  {
    id: 'r19',
    productName: 'Набор органайзеров прозрачных',
    productBarcode: 'AHMA1OR501TR',
    channel: 'OZON',
    rating: 3,
    text: 'Размер чуть меньше, чем казалось по фото. В целом ок, но не вау.',
    author: 'Кристина Ш.',
    date: '2026-05-14T18:00:00Z',
    sentiment: 'neutral',
    responseStatus: 'pending',
  },
  {
    id: 'r20',
    productName: 'Подставка для планшета',
    productBarcode: 'ACRA1ST201BL',
    channel: 'WB',
    rating: 5,
    text: 'Лёгкая, складная, ставлю на кухне для рецептов. Очень довольна покупкой.',
    author: 'Лариса И.',
    date: '2026-05-13T11:55:00Z',
    sentiment: 'positive',
    responseStatus: 'answered',
    responseText: 'Спасибо!',
    responseDate: '2026-05-13T14:00:00Z',
  },
];

export function buildReviewsSummary(rows: Review[]): ReviewsSummary {
  const total = rows.length;
  const ratingDistribution: Record<1 | 2 | 3 | 4 | 5, number> = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 };
  let sumRating = 0;
  let positive = 0;
  let negative = 0;
  let answered = 0;
  for (const r of rows) {
    sumRating += r.rating;
    ratingDistribution[r.rating as ReviewRating] += 1;
    if (r.sentiment === 'positive') positive += 1;
    if (r.sentiment === 'negative') negative += 1;
    if (r.responseStatus === 'answered') answered += 1;
  }
  return {
    totalReviews: total,
    avgRating: total ? sumRating / total : 0,
    avgRatingDelta: 3,
    positiveShare: total ? (positive / total) * 100 : 0,
    negativeShare: total ? (negative / total) * 100 : 0,
    responseRate: total ? (answered / total) * 100 : 0,
    ratingDistribution,
  };
}

export const mockReviewsSummary = buildReviewsSummary(mockReviews);
