import type { DeficitRow, DeficitSummary } from './types';

export const mockDeficitRows: DeficitRow[] = [
  {
    id: '1',
    name: 'Таблетница на неделю — 2 приема круглая серая',
    barcode: 'ACRA7TB301GR',
    channel: 'WB',
    warehouse: 'Сарапул',
    tags: ['PPP', 'A', 'Z'],
    lostRevenue: 32,
    forecastDemand: 1200,
    daysLeft: 0,
    toSupply: 1,
    dailySales: 0.03,
    stock: 0,
  },
  {
    id: '2',
    name: 'Бандаж для лица подбородка многоразовый силиконовый',
    barcode: 'ACRF1BN201GR',
    channel: 'WB',
    warehouse: 'Тула',
    tags: ['PPP', 'A', 'Z'],
    lostRevenue: 681,
    forecastDemand: 8400,
    daysLeft: 0,
    toSupply: 1,
    dailySales: 0.03,
    stock: 0,
  },
  {
    id: '3',
    name: 'Таблетница на неделю 2 приема',
    barcode: 'ACRB1MS106WH',
    channel: 'WB',
    warehouse: 'Астана 2',
    tags: ['PPP', 'A', 'Y'],
    lostRevenue: 639,
    forecastDemand: 7200,
    daysLeft: 0,
    toSupply: 1,
    dailySales: 0.03,
    stock: 0,
  },
  {
    id: '4',
    name: 'Большой мешок для стирки — 60×80 сетка крупная',
    barcode: 'AHMA3BW202WH',
    channel: 'WB',
    warehouse: 'СЦ Волгоград',
    tags: ['PPP', 'A', 'Y'],
    lostRevenue: 22,
    forecastDemand: 980,
    daysLeft: 0,
    toSupply: 1,
    dailySales: 0.03,
    stock: 0,
  },
  {
    id: '5',
    name: 'Мешок для стирки белья — сетка крупная — 3 штуки',
    barcode: 'ACRF1MS301WH',
    channel: 'WB',
    warehouse: 'Электросталь',
    tags: ['PPP', 'A', 'Y'],
    lostRevenue: 2253,
    forecastDemand: 28000,
    daysLeft: 0,
    toSupply: 12,
    dailySales: 0.4,
    stock: 0,
  },
  {
    id: '6',
    name: 'Таблетница на неделю 2 приема чёрная',
    barcode: 'ACRA7TB301BL',
    channel: 'WB',
    warehouse: 'СЦ Волгоград',
    tags: ['PPP', 'A', 'Y'],
    lostRevenue: 472,
    forecastDemand: 5600,
    daysLeft: 0,
    toSupply: 1,
    dailySales: 0.03,
    stock: 0,
  },
  {
    id: '7',
    name: 'Мяч массажный для стоп с шипами',
    barcode: 'ACRM1MS501WH',
    channel: 'WB',
    warehouse: 'Тула',
    tags: ['PP', 'B', 'Z'],
    lostRevenue: 252,
    forecastDemand: 3100,
    daysLeft: 0,
    toSupply: 1,
    dailySales: 0.03,
    stock: 0,
  },
  {
    id: '8',
    name: 'Шар мфр для пилатеса фитнес мяч',
    barcode: 'ACRM2MS302BL',
    channel: 'OZON',
    warehouse: 'Хоругвино',
    tags: ['PP', 'A', 'Y'],
    lostRevenue: 1840,
    forecastDemand: 15600,
    daysLeft: 2,
    toSupply: 8,
    dailySales: 1.2,
    stock: 3,
  },
  {
    id: '9',
    name: 'Бандаж для лица прозрачный',
    barcode: 'ACRF1BN202CL',
    channel: 'OZON',
    warehouse: 'Тверь',
    tags: ['P', 'B', 'Y'],
    lostRevenue: 980,
    forecastDemand: 7800,
    daysLeft: 3,
    toSupply: 5,
    dailySales: 0.5,
    stock: 2,
  },
  {
    id: '10',
    name: 'Набор органайзеров прозрачных',
    barcode: 'AHMA1OR501TR',
    channel: 'WB',
    warehouse: 'Казань',
    tags: ['PP', 'B', 'X'],
    lostRevenue: 510,
    forecastDemand: 5200,
    daysLeft: 5,
    toSupply: 6,
    dailySales: 0.8,
    stock: 4,
  },
  {
    id: '11',
    name: 'Подставка для планшета',
    barcode: 'ACRA1ST201BL',
    channel: 'OZON',
    warehouse: 'Тверь',
    tags: ['P', 'C', 'X'],
    lostRevenue: 120,
    forecastDemand: 1900,
    daysLeft: 7,
    toSupply: 3,
    dailySales: 0.3,
    stock: 2,
  },
  {
    id: '12',
    name: 'Кольцо для пилатеса мягкое',
    barcode: 'ACRP1RG301GR',
    channel: 'WB',
    warehouse: 'Сарапул',
    tags: ['PP', 'B', 'X'],
    lostRevenue: 0,
    forecastDemand: 4200,
    daysLeft: 12,
    toSupply: 0,
    dailySales: 0.4,
    stock: 5,
  },
];

export function buildDeficitSummary(rows: DeficitRow[]): DeficitSummary {
  return {
    totalLostRevenue: rows.reduce((acc, r) => acc + r.lostRevenue, 0),
    outOfStockCount: rows.filter((r) => r.stock === 0).length,
    criticalCount: rows.filter((r) => r.daysLeft < 3).length,
    warningCount: rows.filter((r) => r.daysLeft >= 3 && r.daysLeft <= 7).length,
    totalRows: rows.length,
  };
}

export const mockDeficitSummary = buildDeficitSummary(mockDeficitRows);
